In [2]:

import pandas as pd
import csv
from sqlalchemy import create_engine

import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
import numpy as np

In [6]:
file_one = "ETL/Data/2020Crashes.csv"

In [7]:
crashes2020 = pd.read_csv(file_one, encoding="ISO-8859-1")

In [8]:
crashes2020.head()

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,01/02/2020,12:57,NaN,NaN,NaN,NaN,NaN,W 57 & 8th Ave,W 57,NaN,...,Unspecified,NaN,NaN,NaN,4268255,Taxi,Pick-up Truck,NaN,NaN,NaN
1,01/02/2020,20:00,NaN,NaN,NaN,NaN,NaN,ALAMEDA AVENUE,NORTHERN BOULEVARD,NaN,...,Unspecified,NaN,NaN,NaN,4268437,Sedan,Sedan,NaN,NaN,NaN
2,01/02/2020,22:57,NaN,NaN,NaN,NaN,NaN,LIBERTY AVENUE,VANWYCK EXPRESSWAY,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,4270521,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
3,01/02/2020,15:14,BROOKLYN,11206.0,40.698376,-73.937710,"(40.698376, -73.93771)",NaN,NaN,871 BROADWAY,...,Unspecified,NaN,NaN,NaN,4354121,suburban,moped,NaN,NaN,NaN
4,01/02/2020,0:00,MANHATTAN,10030.0,40.817886,-73.945526,"(40.817886, -73.945526)",NaN,NaN,2570 8 AVENUE,...,Driver Inexperience,NaN,NaN,NaN,4267966,Sedan,Taxi,NaN,NaN,NaN

In [9]:
del crashes2020['ON STREET NAME']
del crashes2020['CROSS STREET NAME']
del crashes2020['OFF STREET NAME']
del crashes2020['CONTRIBUTING FACTOR VEHICLE 3']
del crashes2020['CONTRIBUTING FACTOR VEHICLE 4']
del crashes2020['CONTRIBUTING FACTOR VEHICLE 5']
del crashes2020['VEHICLE TYPE CODE 3']
del crashes2020['VEHICLE TYPE CODE 4']
del crashes2020['VEHICLE TYPE CODE 5']

In [10]:
crashes2020

crashes2020 = crashes2020[crashes2020['BOROUGH'].notna()]

In [11]:
crashes2020 = crashes2020[crashes2020['LATITUDE'].notna()]

In [12]:
crashes2020 = crashes2020[crashes2020['LONGITUDE'].notna()]

In [13]:
crashes2020

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2
3,01/02/2020,15:14,BROOKLYN,11206.0,40.698376,-73.937710,"(40.698376, -73.93771)",1,0,0,0,0,0,1,0,Pedestrian/Bicyclist/Other Pedestrian Error/Co...,Unspecified,4354121,suburban,moped
4,01/02/2020,0:00,MANHATTAN,10030.0,40.817886,-73.945526,"(40.817886, -73.945526)",0,0,0,0,0,0,0,0,Driver Inattention/Distraction,Driver Inexperience,4267966,Sedan,Taxi
10,01/02/2020,15:00,MANHATTAN,10002.0,40.714085,-73.982506,"(40.714085, -73.982506)",0,0,0,0,0,0,0,0,Unspecified,NaN,4268280,Sedan,NaN
12,01/02/2020,20:06,MANHATTAN,10022.0,40.757637,-73.963420,"(40.757637, -73.96342)",1,0,1,0,0,0,0,0,Driver Inattention/Distraction,NaN,4268125,Station Wagon/Sport Utility Vehicle,NaN
13,01/02/2020,18:00,BROOKLYN,11236.0,40.653896,-73.901420,"(40.653896, -73.90142)",3,0,0,0,0,0,3,0,Failure to Yield Right-of-Way,Unspecified,4271706,Station Wagon/Sport Utility Vehicle,Sedan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105910,12/08/2020,17:34,BROOKLYN,11217.0,40.686756,-73.975525,"(40.686756, -73.975525)",1,0,1,0,0,0,0,0,Driver Inattention/Distraction,NaN,4374330,Station Wagon/Sport Utility Vehicle,NaN
105911,12/08/2020,9:53,BROOKLYN,11207.0,40.654080,-73.891620,"(40.65408, -73.89162)",0,0,0,0,0,0,0,0,Unspecified,Unspecified,4374545,Box Truck,Station Wagon/Sport Utility Vehicle
105912,12/08/2020,18:00,BROOKLYN,11214.0,40.583664,-73.986560,"(40.583664, -73.98656)",0,0,0,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,4374392,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
105914,12/08/2020,9:00,MANHATTAN,10022.0,40.761610,-73.970760,"(40.76161, -73.97076)",0,0,0,0,0,0,0,0,Failure to Yield Right-of-Way,Unspecified,4374197,Taxi,Sedan
105915,12/08/2020,9:34,BRONX,10451.0,40.824970,-73.922280,"(40.82497, -73.92228)",0,0,0,0,0,0,0,0,Passing Too Closely,Oversized Vehicle,4374371,Box Truck,Sedan

In [14]:
del crashes2020['CONTRIBUTING FACTOR VEHICLE 2']
del crashes2020['VEHICLE TYPE CODE 2']

In [15]:
crashes2020_df = crashes2020.rename(columns={"CRASH DATE":"CrashDate", "CRASH TIME": "CrashTime", "ZIP CODE": "ZipCode",
                                            "NUMBER OF PERSONS INJURED": "PersonsInjured", "NUMBER OF PERSONS KILLED": "PersonsKilled",
                                            "NUMBER OF PEDESTRIANS INJURED": "PedestriansInjured", "NUMBER OF PEDESTRIANS KILLED": "PedestriansKilled", 
                                            "NUMBER OF CYCLIST INJURED": "CyclistInjured", "NUMBER OF CYCLIST KILLED": "CyclistKilled",
                                            "NUMBER OF MOTORIST INJURED": "MotoristInjured", "NUMBER OF MOTORIST KILLED": "MotoristKilled",
                                            "CONTRIBUTING FACTOR VEHICLE 1": "ContributingFactor", "VEHICLE TYPE CODE 1": "VehicleType"})

In [16]:
crashes2020_df

,CrashDate,CrashTime,BOROUGH,ZipCode,LATITUDE,LONGITUDE,LOCATION,PersonsInjured,PersonsKilled,PedestriansInjured,PedestriansKilled,CyclistInjured,CyclistKilled,MotoristInjured,MotoristKilled,ContributingFactor,COLLISION_ID,VehicleType
3,01/02/2020,15:14,BROOKLYN,11206.0,40.698376,-73.937710,"(40.698376, -73.93771)",1,0,0,0,0,0,1,0,Pedestrian/Bicyclist/Other Pedestrian Error/Co...,4354121,suburban
4,01/02/2020,0:00,MANHATTAN,10030.0,40.817886,-73.945526,"(40.817886, -73.945526)",0,0,0,0,0,0,0,0,Driver Inattention/Distraction,4267966,Sedan
10,01/02/2020,15:00,MANHATTAN,10002.0,40.714085,-73.982506,"(40.714085, -73.982506)",0,0,0,0,0,0,0,0,Unspecified,4268280,Sedan
12,01/02/2020,20:06,MANHATTAN,10022.0,40.757637,-73.963420,"(40.757637, -73.96342)",1,0,1,0,0,0,0,0,Driver Inattention/Distraction,4268125,Station Wagon/Sport Utility Vehicle
13,01/02/2020,18:00,BROOKLYN,11236.0,40.653896,-73.901420,"(40.653896, -73.90142)",3,0,0,0,0,0,3,0,Failure to Yield Right-of-Way,4271706,Station Wagon/Sport Utility Vehicle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105910,12/08/2020,17:34,BROOKLYN,11217.0,40.686756,-73.975525,"(40.686756, -73.975525)",1,0,1,0,0,0,0,0,Driver Inattention/Distraction,4374330,Station Wagon/Sport Utility Vehicle
105911,12/08/2020,9:53,BROOKLYN,11207.0,40.654080,-73.891620,"(40.65408, -73.89162)",0,0,0,0,0,0,0,0,Unspecified,4374545,Box Truck
105912,12/08/2020,18:00,BROOKLYN,11214.0,40.583664,-73.986560,"(40.583664, -73.98656)",0,0,0,0,0,0,0,0,Driver Inattention/Distraction,4374392,Station Wagon/Sport Utility Vehicle
105914,12/08/2020,9:00,MANHATTAN,10022.0,40.761610,-73.970760,"(40.76161, -73.97076)",0,0,0,0,0,0,0,0,Failure to Yield Right-of-Way,4374197,Taxi
105915,12/08/2020,9:34,BRONX,10451.0,40.824970,-73.922280,"(40.82497, -73.92228)",0,0,0,0,0,0,0,0,Passing Too Closely,4374371,Box Truck

In [17]:
crashes2020_df = crashes2020_df.rename(columns={"BOROUGH":"Borough", "LATITUDE": "Latitude", "LONGITUDE": "Longitude", 
                                                "LOCATION": "Location", "COLLISION_ID": "CollisionID"})

In [18]:
crashes2020_df

,CrashDate,CrashTime,Borough,ZipCode,Latitude,Longitude,Location,PersonsInjured,PersonsKilled,PedestriansInjured,PedestriansKilled,CyclistInjured,CyclistKilled,MotoristInjured,MotoristKilled,ContributingFactor,CollisionID,VehicleType
3,01/02/2020,15:14,BROOKLYN,11206.0,40.698376,-73.937710,"(40.698376, -73.93771)",1,0,0,0,0,0,1,0,Pedestrian/Bicyclist/Other Pedestrian Error/Co...,4354121,suburban
4,01/02/2020,0:00,MANHATTAN,10030.0,40.817886,-73.945526,"(40.817886, -73.945526)",0,0,0,0,0,0,0,0,Driver Inattention/Distraction,4267966,Sedan
10,01/02/2020,15:00,MANHATTAN,10002.0,40.714085,-73.982506,"(40.714085, -73.982506)",0,0,0,0,0,0,0,0,Unspecified,4268280,Sedan
12,01/02/2020,20:06,MANHATTAN,10022.0,40.757637,-73.963420,"(40.757637, -73.96342)",1,0,1,0,0,0,0,0,Driver Inattention/Distraction,4268125,Station Wagon/Sport Utility Vehicle
13,01/02/2020,18:00,BROOKLYN,11236.0,40.653896,-73.901420,"(40.653896, -73.90142)",3,0,0,0,0,0,3,0,Failure to Yield Right-of-Way,4271706,Station Wagon/Sport Utility Vehicle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105910,12/08/2020,17:34,BROOKLYN,11217.0,40.686756,-73.975525,"(40.686756, -73.975525)",1,0,1,0,0,0,0,0,Driver Inattention/Distraction,4374330,Station Wagon/Sport Utility Vehicle
105911,12/08/2020,9:53,BROOKLYN,11207.0,40.654080,-73.891620,"(40.65408, -73.89162)",0,0,0,0,0,0,0,0,Unspecified,4374545,Box Truck
105912,12/08/2020,18:00,BROOKLYN,11214.0,40.583664,-73.986560,"(40.583664, -73.98656)",0,0,0,0,0,0,0,0,Driver Inattention/Distraction,4374392,Station Wagon/Sport Utility Vehicle
105914,12/08/2020,9:00,MANHATTAN,10022.0,40.761610,-73.970760,"(40.76161, -73.97076)",0,0,0,0,0,0,0,0,Failure to Yield Right-of-Way,4374197,Taxi
105915,12/08/2020,9:34,BRONX,10451.0,40.824970,-73.922280,"(40.82497, -73.92228)",0,0,0,0,0,0,0,0,Passing Too Closely,4374371,Box Truck

In [19]:
del crashes2020_df['Location']

In [20]:
crashes2020_df["CrashDate"] = pd.to_datetime(crashes2020_df["CrashDate"]).dt.strftime('%Y-%m-%d')
print(crashes2020_df)

         CrashDate CrashTime    Borough  ZipCode   Latitude  Longitude  \
3       2020-01-02     15:14   BROOKLYN  11206.0  40.698376 -73.937710
4       2020-01-02      0:00  MANHATTAN  10030.0  40.817886 -73.945526
10      2020-01-02     15:00  MANHATTAN  10002.0  40.714085 -73.982506
12      2020-01-02     20:06  MANHATTAN  10022.0  40.757637 -73.963420
13      2020-01-02     18:00   BROOKLYN  11236.0  40.653896 -73.901420
...            ...       ...        ...      ...        ...        ...
105910  2020-12-08     17:34   BROOKLYN  11217.0  40.686756 -73.975525
105911  2020-12-08      9:53   BROOKLYN  11207.0  40.654080 -73.891620
105912  2020-12-08     18:00   BROOKLYN  11214.0  40.583664 -73.986560
105914  2020-12-08      9:00  MANHATTAN  10022.0  40.761610 -73.970760
105915  2020-12-08      9:34      BRONX  10451.0  40.824970 -73.922280

        PersonsInjured  PersonsKilled  PedestriansInjured  PedestriansKilled  \
3                    1              0                   0                  0
4                    0              0                   0                  0
10                   0              0                   0                  0
12                   1              0                   1                  0
13                   3              0                   0                  0
...                ...            ...                 ...                ...
105910               1              0                   1                  0
105911               0              0                   0                  0
105912               0              0                   0                  0
105914               0              0                   0                  0
105915               0              0                   0                  0

        CyclistInjured  CyclistKilled  MotoristInjured  MotoristKilled  \
3                    0              0                1               0
4                    0              0                0               0
10                   0              0                0               0
12                   0              0                0               0
13                   0              0                3               0
...                ...            ...              ...             ...
105910               0              0                0               0
105911               0              0                0               0
105912               0              0                0               0
105914               0              0                0               0
105915               0              0                0               0

                                       ContributingFactor  CollisionID  \
3       Pedestrian/Bicyclist/Other Pedestrian Error/Co...      4354121
4                          Driver Inattention/Distraction      4267966
10                                            Unspecified      4268280
12                         Driver Inattention/Distraction      4268125
13                          Failure to Yield Right-of-Way      4271706
...                                                   ...          ...
105910                     Driver Inattention/Distraction      4374330
105911                                        Unspecified      4374545
105912                     Driver Inattention/Distraction      4374392
105914                      Failure to Yield Right-of-Way      4374197
105915                                Passing Too Closely      4374371

                                VehicleType
3                                  suburban
4                                     Sedan
10                                    Sedan
12      Station Wagon/Sport Utility Vehicle
13      Station Wagon/Sport Utility Vehicle
...                                     ...
105910  Station Wagon/Sport Utility Vehicle
105911                            Box Truck
105912  Station Wagon/Sport Utility Vehicle
105914                                 Taxi
105915                            Box Truck

[67229 rows x 17 columns]

In [21]:
crashes2020_df.head()

,CrashDate,CrashTime,Borough,ZipCode,Latitude,Longitude,PersonsInjured,PersonsKilled,PedestriansInjured,PedestriansKilled,CyclistInjured,CyclistKilled,MotoristInjured,MotoristKilled,ContributingFactor,CollisionID,VehicleType
3,2020-01-02,15:14,BROOKLYN,11206.0,40.698376,-73.937710,1,0,0,0,0,0,1,0,Pedestrian/Bicyclist/Other Pedestrian Error/Co...,4354121,suburban
4,2020-01-02,0:00,MANHATTAN,10030.0,40.817886,-73.945526,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,4267966,Sedan
10,2020-01-02,15:00,MANHATTAN,10002.0,40.714085,-73.982506,0,0,0,0,0,0,0,0,Unspecified,4268280,Sedan
12,2020-01-02,20:06,MANHATTAN,10022.0,40.757637,-73.963420,1,0,1,0,0,0,0,0,Driver Inattention/Distraction,4268125,Station Wagon/Sport Utility Vehicle
13,2020-01-02,18:00,BROOKLYN,11236.0,40.653896,-73.901420,3,0,0,0,0,0,3,0,Failure to Yield Right-of-Way,4271706,Station Wagon/Sport Utility Vehicle

In [22]:
del crashes2020_df['ZipCode']

In [23]:
crashes2020_df

,CrashDate,CrashTime,Borough,Latitude,Longitude,PersonsInjured,PersonsKilled,PedestriansInjured,PedestriansKilled,CyclistInjured,CyclistKilled,MotoristInjured,MotoristKilled,ContributingFactor,CollisionID,VehicleType
3,2020-01-02,15:14,BROOKLYN,40.698376,-73.937710,1,0,0,0,0,0,1,0,Pedestrian/Bicyclist/Other Pedestrian Error/Co...,4354121,suburban
4,2020-01-02,0:00,MANHATTAN,40.817886,-73.945526,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,4267966,Sedan
10,2020-01-02,15:00,MANHATTAN,40.714085,-73.982506,0,0,0,0,0,0,0,0,Unspecified,4268280,Sedan
12,2020-01-02,20:06,MANHATTAN,40.757637,-73.963420,1,0,1,0,0,0,0,0,Driver Inattention/Distraction,4268125,Station Wagon/Sport Utility Vehicle
13,2020-01-02,18:00,BROOKLYN,40.653896,-73.901420,3,0,0,0,0,0,3,0,Failure to Yield Right-of-Way,4271706,Station Wagon/Sport Utility Vehicle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105910,2020-12-08,17:34,BROOKLYN,40.686756,-73.975525,1,0,1,0,0,0,0,0,Driver Inattention/Distraction,4374330,Station Wagon/Sport Utility Vehicle
105911,2020-12-08,9:53,BROOKLYN,40.654080,-73.891620,0,0,0,0,0,0,0,0,Unspecified,4374545,Box Truck
105912,2020-12-08,18:00,BROOKLYN,40.583664,-73.986560,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,4374392,Station Wagon/Sport Utility Vehicle
105914,2020-12-08,9:00,MANHATTAN,40.761610,-73.970760,0,0,0,0,0,0,0,0,Failure to Yield Right-of-Way,4374197,Taxi
105915,2020-12-08,9:34,BRONX,40.824970,-73.922280,0,0,0,0,0,0,0,0,Passing Too Closely,4374371,Box Truck

In [24]:
crashes2020_df=crashes2020_df.round({'Latitude': 4, 'Longitude': 4})

In [25]:
crashes2020_df

,CrashDate,CrashTime,Borough,Latitude,Longitude,PersonsInjured,PersonsKilled,PedestriansInjured,PedestriansKilled,CyclistInjured,CyclistKilled,MotoristInjured,MotoristKilled,ContributingFactor,CollisionID,VehicleType
3,2020-01-02,15:14,BROOKLYN,40.6984,-73.9377,1,0,0,0,0,0,1,0,Pedestrian/Bicyclist/Other Pedestrian Error/Co...,4354121,suburban
4,2020-01-02,0:00,MANHATTAN,40.8179,-73.9455,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,4267966,Sedan
10,2020-01-02,15:00,MANHATTAN,40.7141,-73.9825,0,0,0,0,0,0,0,0,Unspecified,4268280,Sedan
12,2020-01-02,20:06,MANHATTAN,40.7576,-73.9634,1,0,1,0,0,0,0,0,Driver Inattention/Distraction,4268125,Station Wagon/Sport Utility Vehicle
13,2020-01-02,18:00,BROOKLYN,40.6539,-73.9014,3,0,0,0,0,0,3,0,Failure to Yield Right-of-Way,4271706,Station Wagon/Sport Utility Vehicle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105910,2020-12-08,17:34,BROOKLYN,40.6868,-73.9755,1,0,1,0,0,0,0,0,Driver Inattention/Distraction,4374330,Station Wagon/Sport Utility Vehicle
105911,2020-12-08,9:53,BROOKLYN,40.6541,-73.8916,0,0,0,0,0,0,0,0,Unspecified,4374545,Box Truck
105912,2020-12-08,18:00,BROOKLYN,40.5837,-73.9866,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,4374392,Station Wagon/Sport Utility Vehicle
105914,2020-12-08,9:00,MANHATTAN,40.7616,-73.9708,0,0,0,0,0,0,0,0,Failure to Yield Right-of-Way,4374197,Taxi
105915,2020-12-08,9:34,BRONX,40.8250,-73.9223,0,0,0,0,0,0,0,0,Passing Too Closely,4374371,Box Truck

In [34]:
crashes2020_df.to_csv("ETL/Data/NYC2020crashes.csv", index=False, header=True)

In [35]:
html_table = crashes2020_df.to_html()

In [36]:
crashes2020_df.to_html('Web/table.html')

In [37]:
crashes2020_df.to_json(r'Path to store the exported JSON file\File Name.json')

# Borough Totals

In [26]:
crashes2020_df

,CrashDate,CrashTime,Borough,Latitude,Longitude,PersonsInjured,PersonsKilled,PedestriansInjured,PedestriansKilled,CyclistInjured,CyclistKilled,MotoristInjured,MotoristKilled,ContributingFactor,CollisionID,VehicleType
3,2020-01-02,15:14,BROOKLYN,40.6984,-73.9377,1,0,0,0,0,0,1,0,Pedestrian/Bicyclist/Other Pedestrian Error/Co...,4354121,suburban
4,2020-01-02,0:00,MANHATTAN,40.8179,-73.9455,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,4267966,Sedan
10,2020-01-02,15:00,MANHATTAN,40.7141,-73.9825,0,0,0,0,0,0,0,0,Unspecified,4268280,Sedan
12,2020-01-02,20:06,MANHATTAN,40.7576,-73.9634,1,0,1,0,0,0,0,0,Driver Inattention/Distraction,4268125,Station Wagon/Sport Utility Vehicle
13,2020-01-02,18:00,BROOKLYN,40.6539,-73.9014,3,0,0,0,0,0,3,0,Failure to Yield Right-of-Way,4271706,Station Wagon/Sport Utility Vehicle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105910,2020-12-08,17:34,BROOKLYN,40.6868,-73.9755,1,0,1,0,0,0,0,0,Driver Inattention/Distraction,4374330,Station Wagon/Sport Utility Vehicle
105911,2020-12-08,9:53,BROOKLYN,40.6541,-73.8916,0,0,0,0,0,0,0,0,Unspecified,4374545,Box Truck
105912,2020-12-08,18:00,BROOKLYN,40.5837,-73.9866,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,4374392,Station Wagon/Sport Utility Vehicle
105914,2020-12-08,9:00,MANHATTAN,40.7616,-73.9708,0,0,0,0,0,0,0,0,Failure to Yield Right-of-Way,4374197,Taxi
105915,2020-12-08,9:34,BRONX,40.8250,-73.9223,0,0,0,0,0,0,0,0,Passing Too Closely,4374371,Box Truck

In [37]:
crash_count = crashes2020_df.groupby(['Borough']).count()
crash_count

,CrashDate,CrashTime,Latitude,Longitude,PersonsInjured,PersonsKilled,PedestriansInjured,PedestriansKilled,CyclistInjured,CyclistKilled,MotoristInjured,MotoristKilled,ContributingFactor,CollisionID,VehicleType
Borough,,,,,,,,,,,,,,,
BRONX,12937,12937,12937,12937,12937,12937,12937,12937,12937,12937,12937,12937,12847,12937,12751
BROOKLYN,23395,23395,23395,23395,23395,23395,23395,23395,23395,23395,23395,23395,23281,23395,23159
MANHATTAN,9915,9915,9915,9915,9915,9915,9915,9915,9915,9915,9915,9915,9861,9915,9808
QUEENS,18881,18881,18881,18881,18881,18881,18881,18881,18881,18881,18881,18881,18802,18881,18695
STATEN ISLAND,2101,2101,2101,2101,2101,2101,2101,2101,2101,2101,2101,2101,2094,2101,2080

In [38]:
crash_count = crash_count.rename(columns={"CrashDate": "CrashCount"})

In [45]:
del crash_count['CrashTime']
del crash_count['Latitude']
del crash_count['Longitude']
del crash_count['PersonsInjured']
del crash_count['PersonsKilled']
del crash_count['PedestriansInjured']
del crash_count['PedestriansKilled']
del crash_count['CyclistInjured']
del crash_count['CyclistKilled']
del crash_count['MotoristInjured']
del crash_count['MotoristKilled']
del crash_count['ContributingFactor']
del crash_count['CollisionID']
del crash_count['VehicleType']

In [62]:
crashcount = crash_count.reset_index()

In [63]:
crashcount.to_csv("Data/CrashCount.csv", index=False, header=True)

In [48]:
crash_impact = crashes2020_df.groupby(['Borough']).sum()
crash_impact

,Latitude,Longitude,PersonsInjured,PersonsKilled,PedestriansInjured,PedestriansKilled,CyclistInjured,CyclistKilled,MotoristInjured,MotoristKilled,CollisionID
Borough,,,,,,,,,,,
BRONX,527379.5635,-9.539012e+05,4688,19,896,7,581,4,3211,8,55926123546
BROOKLYN,949544.0617,-1.727092e+06,8915,37,1631,15,1456,6,5828,16,101115965118
MANHATTAN,403545.5562,-7.321553e+05,3256,18,784,8,886,3,1586,7,42827361307
QUEENS,767398.7535,-1.391554e+06,6635,44,1183,19,795,1,4657,24,81565362725
STATEN ISLAND,84841.1402,-1.549078e+05,834,8,105,3,44,0,685,5,9087802546

In [53]:
#del crash_impact['Latitude']
#del crash_impact['Longitude']
del crash_impact['CollisionID']

In [60]:
crashimpact = crash_impact.reset_index()

In [61]:
crashimpact.to_csv("Data/CrashImpacts.csv", index=False, header=True)